name: 'CSV Combiner'
description: 'A GitHub Action to combine two CSV files based on user-defined columns and modes.'

inputs:
  base_csv_file:
    description: 'Path to the base CSV file.'
    required: true
  additional_csv_file:
    description: 'Path to the additional CSV file.'
    required: true
  output_file:
    description: 'Path to the output CSV file.'
    required: true
  header_column:
    description: 'Column in the "additional" CSV to use as headers in the combined CSV. Only required for default mode'
    required: false
  base_csv_columns:
    description: 'Comma-separated list of columns in the base CSV to check for equality.'
    required: true
  additional_csv_columns:
    description: 'Comma-separated list of columns in the additional CSV to check for equality. These columns will not be written to the output CSV in direct mode.'
    required: true
  mode:
    description: 'Mode of operation (default or direct).'
    required: false
    default: 'default'

runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'file-csv'
  color: 'blue'